---
platform: linux

image_resource:
  type: docker-image
  source: { repository: onsdigital/paas-ci-gp, tag: latest }

inputs:
- name: paas-bootstrap-git
- name: vpc-tfstate-s3

outputs:
- name: vpc-vars

run:
  path: paas-bootstrap-git/ci/tasks/bosh/get_terraform_vars/task.sh
