---
platform: linux

image_resource:
  type: docker-image
  source: { repository: governmentpaas/awscli, tag: latest }

inputs:
- name: paas-bootstrap-git

run:
  path: paas-bootstrap-git/ci/tasks/concourse/test_iam_policy/task.sh

