---
platform: linux
image_resource:
  type: docker-image
  source: { repository: onsdigital/paas-ci-gp, tag: latest }

inputs:
  - name: paas-bootstrap-git
  - name: cf-manifests

outputs:

run:
  path: paas-bootstrap-git/ci/tasks/cf/deploy_cf/task.sh

