---
platform: linux

image_resource:
  type: docker-image
  source: { repository: onsdigital/paas-ci-gp, tag: latest }

inputs:
- name: paas-bootstrap-git

outputs:
- name: vpc-vars

run:
  path: git-repo/jumpbox/scripts/get_terraform_vars.sh

