---
platform: linux

image_resource:
  type: docker-image
  source: { repository: onsdigital/paas-ci-gp, tag: latest }

inputs:
- name: git-repo

run:
  path: git-repo/jumpbox/scripts/test.sh

params:
  ENVIRONMENT: ((environment))
