---
platform: linux

image_resource:
  type: docker-image
  source: { repository: onsdigital/paas-ci-gp, tag: latest }

inputs:
- name: paas-bootstrap-git

run:
  path: paas-bootstrap-git/jumpbox/scripts/test.sh

params:
  ENVIRONMENT: ((environment))
