org: paas
org-billingmanager:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: []
org-manager:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: []
org-auditor:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: []
private-domains: []
enable-remove-private-domains: true
shared-private-domains: []
enable-remove-shared-private-domains: true
enable-org-quota: false
memory-limit: 0
instance-memory-limit: 0
total-routes: 0
total-services: 0
paid-service-plans-allowed: false
enable-remove-users: true
total_private_domains: 0
total_reserved_route_ports: 0
total_service_keys: 0
app_instance_limit: 0
default_isolation_segment: ""
