---
platform: linux
image_resource:
  type: docker-image
  source: { repository: onsdigital/paas-ci-gp, tag: latest }

inputs:
  - name: paas-bootstrap-git
  - name: cf_user_credentials
  - name: rds-broker-git

run:
  path: paas-bootstrap-git/ci/tasks/cf/rds-service-broker/task.sh

params:
  ENVIRONMENT:
