---
platform: linux
image_resource:
  type: docker-image
  source: { repository: onsdigital/paas-ci-gp, tag: latest }

inputs:
  - name: paas-bootstrap-git
  - name: cf-deployment-git
  - name: base-tfstate-s3

run:
  path: paas-bootstrap-git/ci/tasks/cf/stemcells/task.sh

params:
  DOMAIN: 
  ENVIRONMENT:
  BOSH_CLIENT: admin
  BOSH_CLIENT_SECRET:
  BOSH_CA_CERT: