---
platform: linux
image_resource:
  type: docker-image
  source: { repository: onsdigital/paas-ci-gp, tag: latest }

inputs:
  - name: paas-bootstrap-git
  - name: bosh-vars-s3
  - name: bosh-manifest-s3

run:
  path: paas-bootstrap-git/ci/tasks/cf/smoke_tests/task.sh
