---
platform: linux
image_resource:
  type: docker-image
  source: { repository: onsdigital/paas-ci-gp, tag: latest }

inputs:
  - name: paas-bootstrap-git
  - name: bosh-state-s3
  - name: bosh-manifest-s3

outputs:
  - name: bosh-state

run:
  path: paas-bootstrap-git/ci/tasks/bosh/deploy/task.sh
