---
resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/ONSdigital/paas-bootstrap.git
    branch: feature/jumpbox

jobs:
- name: pipeline-test
  plan:
  - get: git-repo
  - task: verify
    config:
      environment: ((environment))
    file: git-repo/jumpbox/tasks/test.yml
