---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: robertgruber/terraform-resource

resources:
- name: paas-bootstrap-git
  type: git
  source:
    uri: https://github.com/ONSdigital/paas-bootstrap.git
    branch: feature/jumpbox

- name: jumpbox-terraform
  type: terraform
  source:
    storage:
      bucket: ((environment))-states
      bucket_path: jumpbox/
      use_ec2_role: true
      region_name: ((region))
      server_side_encryption: 'aws:kms'
      sse_kms_key_id: ((s3_kms_key_id))

jobs:
- name: create-network
  plan:
  - get: paas-bootstrap-git
  - task: get-terraform-vars
    file: paas-bootstrap-git/jumpbox/tasks/get_terraform_vars.yml
    params:
      ENVIRONMENT: ((environment))
      S3_KMS_KEY_ID: ((s3_kms_key_id))
  - put: jumpbox-terraform
    params:
      terraform_source: paas-bootstrap-git/terraform/jumpbox/aws
      env_name: ((environment))
      var_files: [vpc-vars/vars.json]

- name: verify-jumpbox
  plan:
  - get: paas-bootstrap-git
    passed: [create-network]
  - task: verify
    file: paas-bootstrap-git/jumpbox/tasks/test.yml
    params:
      ENVIRONMENT: ((environment))

