---
resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/ONSdigital/paas-bootstrap.git
    branch: feature/jumpbox

jobs:
- name: create-network
  plan:
  - get: git-repo
  - task: terraform-make
    file: git-repo/jumpbox/tasks/terraform.yml
    params:
      ENVIRONMENT: ((environment))

- name: verify-jumpbox
  plan:
  - get: git-repo
    passed: [create-network]
  - task: verify
    file: git-repo/jumpbox/tasks/test.yml
    params:
      ENVIRONMENT: ((environment))

