releases:
  - name: node-exporter
    version: 4.0.0

addons:
  - name: node_exporter
    jobs:
      - name: node_exporter
        release: node-exporter
    include:
      stemcell:
        - os: ubuntu-trusty
    properties: {}
