---
platform: linux

image_resource:
  type: docker-image
  source: { repository: onsdigital/paas-ci-gp, tag: latest }

inputs:
  - name: paas-bootstrap-git
  - name: cf-vars-s3

outputs:
  - name: cf_mgmt_vars

run:
  path: paas-bootstrap-git/ci/tasks/cf/management/task.sh

params:
  ENVIRONMENT:
  DOMAIN: