---
platform: linux
image_resource:
  type: docker-image
  source: { repository: onsdigital/paas-ci-gp, tag: latest }

inputs:
  - name: paas-bootstrap-git
  - name: prometheus-deployment-git
  - name: prometheus-vars-s3
  - name: cf-vars-s3
  - name: cf-tfstate-s3
  - name: vpc-tfstate-s3
  - name: bosh-vars-s3
  - name: bosh-tfstate-s3
  - name: prometheus-tfstate-s3

outputs:
  - name: prometheus-manifests

run:
  path: paas-bootstrap-git/ci/tasks/prometheus/interpolate/task.sh

params:
  ENVIRONMENT:
  DOMAIN:
  CF_DEPLOYMENT_NAME:
