---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: robertgruber/terraform-resource

- name: s3-iam
  type: docker-image
  source:
    repository: governmentpaas/s3-resource

resources:
- name: paas-bootstrap-git
  type: git
  source:
    uri: https://github.com/ONSdigital/paas-bootstrap.git
    branch: feature/157509548 

- name: jumpbox-deployment-git
  type: git
  source:
    uri: https://github.com/cppforlife/jumpbox-deployment.git

- name: bosh-deployment-git
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment.git

- name: jumpbox-terraform
  type: terraform
  source:
    storage:
      bucket: ((environment))-states
      bucket_path: jumpbox/
      use_ec2_role: true
      region_name: ((region))
      server_side_encryption: 'aws:kms'
      sse_kms_key_id: ((s3_kms_key_id))

- name: vpc-tfstate-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: vpc/tfstate.json
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

- name: concourse-tfstate-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: concourse/tfstate.json
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

- name: jumpbox-vars-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: jumpbox/jumpbox-variables.yml
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

- name: jumpbox-state-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: jumpbox/jumpbox-state.json
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

- name: jumpbox-manifest-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: jumpbox/jumpbox.yml
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

- name: ssh-private-key-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: concourse/ssh-key.pem
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

- name: bosh-terraform
  type: terraform
  source:
    storage:
      bucket: ((environment))-states
      bucket_path: bosh/
      use_ec2_role: true
      region_name: ((region))
      server_side_encryption: 'aws:kms'
      sse_kms_key_id: ((s3_kms_key_id))

- name: bosh-tfstate-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: bosh/((environment)).tfstate
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

- name: bosh-vars-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: bosh/bosh-variables.yml
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

- name: bosh-state-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: bosh/bosh-state.json
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

- name: bosh-manifest-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: bosh/bosh.yml
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

jobs:
- name: verify-concourse
  serial: true
  plan:
  - get: paas-bootstrap-git
    trigger: true
  - aggregate:
    - task: ensure world cannot connect to concourse on port 22
      file: paas-bootstrap-git/ci/tasks/common/test_connectivity/task.yml
      params:
        HOST: concourse
        DOMAIN: ((domain))
        PORT: 22
        EXPECTED_OUTCOME: failure
    - task: ensure world cannot connect to concourse on port 6868
      file: paas-bootstrap-git/ci/tasks/common/test_connectivity/task.yml
      params:
        HOST: concourse
        DOMAIN: ((domain))
        PORT: 6868
        EXPECTED_OUTCOME: failure
    - task: ensure world cannot connect to concourse (ci) on port 443
      file: paas-bootstrap-git/ci/tasks/common/test_connectivity/task.yml
      params:
        HOST: ci
        DOMAIN: ((domain))
        PORT: 443
        EXPECTED_OUTCOME: failure

- name: terraform-jumpbox
  serial_groups: [main]
  serial: true
  plan:
  - aggregate:
    - get: concourse-tfstate-s3
    - get: vpc-tfstate-s3
    - get: paas-bootstrap-git
  - task: get-terraform-vars
    file: paas-bootstrap-git/ci/tasks/jumpbox/get_terraform_vars/task.yml
  - put: jumpbox-terraform
    params:
      terraform_source: paas-bootstrap-git/terraform/jumpbox/aws
      env_name: ((environment))
      var_files:
      - concourse-vars/vars.json
      - vpc-vars/vars.json

- name: create-jumpbox
  serial_groups: [main]
  serial: true
  plan:
  - aggregate:
    - get: paas-bootstrap-git
      passed: [terraform-jumpbox]
      trigger: true
    - get: jumpbox-deployment-git
      version: { ref: ((jumpbox_commit_ref)) }
    - get: jumpbox-terraform
      passed: [terraform-jumpbox]
    - get: jumpbox-vars-s3
    - get: jumpbox-state-s3
    - get: ssh-private-key-s3
    - get: concourse-tfstate-s3
  - task: interpolate-jumpbox
    file: paas-bootstrap-git/ci/tasks/jumpbox/interpolate/task.yml
    params:
      ENVIRONMENT: ((environment))
    on_success:
      aggregate:
      - put: jumpbox-vars-s3
        params:
          file: jumpbox-manifests/jumpbox-variables.yml
      - put: jumpbox-manifest-s3
        params:
          file: jumpbox-manifests/jumpbox.yml
  - task: deploy-jumpbox
    file: paas-bootstrap-git/ci/tasks/jumpbox/deploy/task.yml
    on_success:
      put: jumpbox-state-s3
      params:
        file: jumpbox-state/jumpbox-state.json
    on_failure:
      put: jumpbox-state-s3
      params:
        file: jumpbox-state/jumpbox-state.json

- name: verify-jumpbox
  serial: true
  plan:
  - get: paas-bootstrap-git
    passed: [create-jumpbox]
    trigger: true
  - aggregate:
    - get: jumpbox-vars-s3
    - get: jumpbox-manifest-s3
  - aggregate:
    - task: ensure concourse can SSH to jumpbox
      file: paas-bootstrap-git/ci/tasks/jumpbox/test/task.yml
      params:
        ENVIRONMENT: ((environment))
    - task: ensure world cannot connect to jumpbox on port 22
      file: paas-bootstrap-git/ci/tasks/common/test_connectivity/task.yml
      params:
        HOST: jumpbox
        DOMAIN: ((domain))
        PORT: 22
        EXPECTED_OUTCOME: failure
    - task: ensure world cannot connect to jumpbox on port 6868
      file: paas-bootstrap-git/ci/tasks/common/test_connectivity/task.yml
      params:
        HOST: jumpbox
        DOMAIN: ((domain))
        PORT: 6868
        EXPECTED_OUTCOME: failure
    - task: ensure that FQDN of jumpbox matches its endpoint
      file: paas-bootstrap-git/ci/tasks/common/test_fqdn/task.yml
      params:
        HOST: jumpbox
        DOMAIN: ((domain))
        EXPECTED_OUTCOME: success

- name: terraform-bosh
  serial_groups: [main]
  serial: true
  plan:
  - aggregate:
    - get: concourse-tfstate-s3
    - get: jumpbox-terraform
    - get: vpc-tfstate-s3
    - get: paas-bootstrap-git
      passed: [verify-jumpbox]
      trigger: true
  - task: get-terraform-vars
    file: paas-bootstrap-git/ci/tasks/bosh/get_terraform_vars/task.yml
  - put: bosh-terraform
    params:
      terraform_source: paas-bootstrap-git/terraform/bosh/aws
      env_name: ((environment))
      var_files:
      - concourse-vars/vars.json
      - jumpbox-terraform/metadata
      - vpc-vars/vars.json

- name: create-bosh
  serial_groups: [main]
  serial: true
  plan:
  - aggregate:
    - get: paas-bootstrap-git
      passed: [terraform-bosh]
      trigger: true
    - get: bosh-deployment-git
      version: { ref: ((bosh_commit_ref)) }
    - get: bosh-terraform
      passed: [terraform-bosh]
    - get: bosh-tfstate-s3
    - get: bosh-vars-s3
    - get: bosh-state-s3
    - get: ssh-private-key-s3
    - get: concourse-tfstate-s3
  - task: interpolate-bosh
    file: paas-bootstrap-git/ci/tasks/bosh/interpolate/task.yml
    params:
      ENVIRONMENT: ((environment))
    on_success:
      aggregate:
      - put: bosh-vars-s3
        params:
          file: bosh-manifests/bosh-variables.yml
      - put: bosh-manifest-s3
        params:
          file: bosh-manifests/bosh.yml
  - task: deploy-bosh
    file: paas-bootstrap-git/ci/tasks/bosh/deploy/task.yml
    on_success:
      put: bosh-state-s3
      params:
        file: bosh-state/bosh-state.json
    on_failure:
      put: bosh-state-s3
      params:
        file: bosh-state/bosh-state.json

- name: verify-bosh
  serial: true
  plan:
  - get: paas-bootstrap-git
    passed: [create-bosh]
    trigger: true
  - aggregate:
    - get: bosh-vars-s3
    - get: bosh-manifest-s3
  - task: verify
    file: paas-bootstrap-git/ci/tasks/bosh/test/task.yml