---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: robertgruber/terraform-resource

- name: s3-iam
  type: docker-image
  source:
    repository: governmentpaas/s3-resource

resources:
- name: paas-bootstrap-git
  type: git
  source:
    uri: https://github.com/ONSdigital/paas-bootstrap.git
    branch: ((branch))

- name: jumpbox-deployment-git
  type: git
  source:
    uri: https://github.com/cppforlife/jumpbox-deployment.git

- name: bosh-deployment-git
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment.git

- name: cf-deployment-git
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment.git

- name: jumpbox-terraform
  type: terraform
  source:
    storage:
      bucket: ((environment))-states
      bucket_path: jumpbox/
      use_ec2_role: true
      region_name: ((region))
      server_side_encryption: 'aws:kms'
      sse_kms_key_id: ((s3_kms_key_id))

- name: vpc-tfstate-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: vpc/tfstate.json
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

- name: concourse-tfstate-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: concourse/tfstate.json
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

- name: jumpbox-tfstate-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: jumpbox/((environment)).tfstate
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

- name: cf-tfstate-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: cf/((environment)).tfstate
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

- name: jumpbox-vars-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: jumpbox/jumpbox-variables.yml
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

- name: jumpbox-state-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: jumpbox/jumpbox-state.json
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

- name: jumpbox-manifest-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: jumpbox/jumpbox.yml
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

- name: ssh-private-key-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: concourse/ssh-key.pem
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

- name: bosh-terraform
  type: terraform
  source:
    storage:
      bucket: ((environment))-states
      bucket_path: bosh/
      use_ec2_role: true
      region_name: ((region))
      server_side_encryption: 'aws:kms'
      sse_kms_key_id: ((s3_kms_key_id))

- name: cf-terraform
  type: terraform
  source:
    storage:
      bucket: ((environment))-states
      bucket_path: cf/
      use_ec2_role: true
      region_name: ((region))
      server_side_encryption: 'aws:kms'
      sse_kms_key_id: ((s3_kms_key_id))
    env:
      TF_LOG: DEBUG  

- name: cf-vars-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: cf/cf-variables.yml
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

- name: cf-manifest-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: cf/cf.yml
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))
    initial_version: "-"
    initial_content_text: |
        ---

- name: cf-cloud-config-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: cf/cloud-config.yml
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

- name: bosh-tfstate-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: bosh/((environment)).tfstate
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

- name: bosh-vars-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: bosh/bosh-variables.yml
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

- name: bosh-state-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: bosh/bosh-state.json
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

- name: bosh-manifest-s3
  type: s3-iam
  source:
    bucket: ((environment))-states
    private: true
    region_name: ((region))
    versioned_file: bosh/bosh.yml
    server_side_encryption: 'aws:kms'
    sse_kms_key_id: ((s3_kms_key_id))

jobs:
- name: verify-concourse
  serial: true
  plan:
  - get: paas-bootstrap-git
    # trigger: true
  - get: concourse-tfstate-s3
  - aggregate:
    - task: ensure world cannot connect to concourse on port 22
      file: paas-bootstrap-git/ci/tasks/common/test_connectivity/task.yml
      params:
        HOST: concourse
        DOMAIN: ((domain))
        PORT: 22
        EXPECTED_OUTCOME: failure
    - task: ensure world cannot connect to concourse on port 6868
      file: paas-bootstrap-git/ci/tasks/common/test_connectivity/task.yml
      params:
        HOST: concourse
        DOMAIN: ((domain))
        PORT: 6868
        EXPECTED_OUTCOME: failure
    - task: ensure world cannot connect to concourse (ci) on port 443
      file: paas-bootstrap-git/ci/tasks/common/test_connectivity/task.yml
      params:
        HOST: ci
        DOMAIN: ((domain))
        PORT: 443
        EXPECTED_OUTCOME: failure
    - task: ensure that direct FQDN of concourse matches its endpoint
      file: paas-bootstrap-git/ci/tasks/concourse/test_fqdn/task.yml
      params:
        HOST: concourse
        DOMAIN: ((domain))
    - task: ensure concourse cannot perform disallowed action
      file: paas-bootstrap-git/ci/tasks/concourse/test_iam_policy/task.yml

- name: terraform-jumpbox
  serial: true
  plan:
  - aggregate:
    - get: concourse-tfstate-s3
    - get: vpc-tfstate-s3
    - get: paas-bootstrap-git
      # trigger: true
  - task: get-terraform-vars
    file: paas-bootstrap-git/ci/tasks/jumpbox/get_terraform_vars/task.yml
  - put: jumpbox-terraform
    params:
      terraform_source: paas-bootstrap-git/terraform/jumpbox/aws
      env_name: ((environment))
      var_files:
      - concourse-vars/vars.json
      - vpc-vars/vars.json

- name: create-jumpbox
  serial: true
  plan:
  - aggregate:
    - get: paas-bootstrap-git
      passed: [terraform-jumpbox]
      trigger: true
    - get: jumpbox-deployment-git
      version: { ref: ((jumpbox_commit_ref)) }
    - get: jumpbox-terraform
      passed: [terraform-jumpbox]
    - get: jumpbox-vars-s3
    - get: jumpbox-state-s3
    - get: ssh-private-key-s3
    - get: concourse-tfstate-s3
  - task: interpolate-jumpbox
    file: paas-bootstrap-git/ci/tasks/jumpbox/interpolate/task.yml
    params:
      ENVIRONMENT: ((environment))
    on_success:
      aggregate:
      - put: jumpbox-vars-s3
        params:
          file: jumpbox-manifests/jumpbox-variables.yml
      - put: jumpbox-manifest-s3
        params:
          file: jumpbox-manifests/jumpbox.yml
  - task: deploy-jumpbox
    file: paas-bootstrap-git/ci/tasks/jumpbox/deploy/task.yml
    on_success:
      put: jumpbox-state-s3
      params:
        file: jumpbox-state/jumpbox-state.json
    on_failure:
      put: jumpbox-state-s3
      params:
        file: jumpbox-state/jumpbox-state.json

- name: verify-jumpbox
  serial: true
  plan:
  - get: paas-bootstrap-git
    passed: [create-jumpbox]
    trigger: true
  - aggregate:
    - get: jumpbox-vars-s3
    - get: jumpbox-manifest-s3
  - aggregate:
    - task: ensure concourse can SSH to jumpbox
      file: paas-bootstrap-git/ci/tasks/jumpbox/test/task.yml
      params:
        ENVIRONMENT: ((environment))
    - task: ensure world cannot connect to jumpbox on port 22
      file: paas-bootstrap-git/ci/tasks/common/test_connectivity/task.yml
      params:
        HOST: jumpbox
        DOMAIN: ((domain))
        PORT: 22
        EXPECTED_OUTCOME: failure
    - task: ensure world cannot connect to jumpbox on port 6868
      file: paas-bootstrap-git/ci/tasks/common/test_connectivity/task.yml
      params:
        HOST: jumpbox
        DOMAIN: ((domain))
        PORT: 6868
        EXPECTED_OUTCOME: failure
    - task: ensure that FQDN of jumpbox matches its endpoint
      file: paas-bootstrap-git/ci/tasks/jumpbox/test_fqdn/task.yml
      params:
        HOST: jumpbox
        DOMAIN: ((domain))

- name: terraform-bosh
  serial: true
  plan:
  - aggregate:
    - get: concourse-tfstate-s3
    - get: jumpbox-terraform
    - get: vpc-tfstate-s3
    - get: paas-bootstrap-git
      passed: [verify-jumpbox]
      trigger: true
  - task: get-terraform-vars
    file: paas-bootstrap-git/ci/tasks/bosh/get_terraform_vars/task.yml
  - put: bosh-terraform
    params:
      terraform_source: paas-bootstrap-git/terraform/bosh/aws
      env_name: ((environment))
      var_files:
      - concourse-vars/vars.json
      - jumpbox-terraform/metadata
      - vpc-vars/vars.json

- name: create-bosh
  serial: true
  plan:
  - aggregate:
    - get: paas-bootstrap-git
      passed: [terraform-bosh]
      trigger: true
    - get: bosh-deployment-git
      version: { ref: ((bosh_commit_ref)) }
    - get: bosh-terraform
      passed: [terraform-bosh]
    - get: bosh-tfstate-s3
    - get: bosh-vars-s3
    - get: bosh-state-s3
    - get: ssh-private-key-s3
    - get: concourse-tfstate-s3
  - task: interpolate-bosh
    file: paas-bootstrap-git/ci/tasks/bosh/interpolate/task.yml
    params:
      ENVIRONMENT: ((environment))
    on_success:
      aggregate:
      - put: bosh-vars-s3
        params:
          file: bosh-manifests/bosh-variables.yml
      - put: bosh-manifest-s3
        params:
          file: bosh-manifests/bosh.yml
  - task: deploy-bosh
    file: paas-bootstrap-git/ci/tasks/bosh/deploy/task.yml
    on_success:
      put: bosh-state-s3
      params:
        file: bosh-state/bosh-state.json

- name: verify-bosh
  serial: true
  plan:
  - get: paas-bootstrap-git
    passed: [create-bosh]
    trigger: true
  - aggregate:
    - get: bosh-vars-s3
    - get: bosh-manifest-s3
  - task: verify
    file: paas-bootstrap-git/ci/tasks/bosh/test/task.yml

- name: terraform-cf
  serial: true
  plan:
  - aggregate:
    - get: vpc-tfstate-s3
    - get: jumpbox-tfstate-s3
    - get: bosh-tfstate-s3
    - get: concourse-tfstate-s3
    - get: paas-bootstrap-git
      trigger: true
      # passed: [verify-bosh]
  - task: get-terraform-vars
    file: paas-bootstrap-git/ci/tasks/cf/get_terraform_vars/task.yml
    params:
      ENVIRONMENT: ((environment))
  - put: cf-terraform
    params:
      terraform_source: paas-bootstrap-git/terraform/cf/aws
      env_name: ((environment))
      var_files:
      - vpc-vars/vars.json
      - jumpbox-vars/vars.json
      - bosh-vars/vars.json
      - concourse-vars/vars.json
      logging: DEBUG

- name: verify-cf
  serial: true
  plan:
  - get: paas-bootstrap-git
    trigger: true
    passed: [terraform-cf]
  - aggregate:
    - task: ensure that system FQDN is resolvable
      file: paas-bootstrap-git/ci/tasks/cf/test/task.yml
      params:
        HOST: test.system
        DOMAIN: ((domain))
    - task: ensure that apps FQDN is resolvable
      file: paas-bootstrap-git/ci/tasks/cf/test/task.yml
      params:
        HOST: test.apps
        DOMAIN: ((domain))

- name: deploy-cf
  serial: true
  plan:
  - aggregate:
    - get: paas-bootstrap-git
      # trigger: true
      passed: [verify-cf]
    - get: cf-deployment-git
      version: { ref: ((cf_commit_ref)) }
    - get: vpc-tfstate-s3
    - get: bosh-tfstate-s3
    - get: cf-tfstate-s3
    - get: cf-vars-s3
    - get: bosh-vars-s3
    - get: bosh-manifest-s3
    - get: cf-manifest-s3
    - get: concourse-tfstate-s3
    - get: jumpbox-tfstate-s3
  - task: get-terraform-vars
    file: paas-bootstrap-git/ci/tasks/cf/get_terraform_vars/task.yml
    params:
      ENVIRONMENT: ((environment))
  - task: interpolate-cf
    file: paas-bootstrap-git/ci/tasks/cf/interpolate/task.yml
    params:
      ENVIRONMENT: ((environment))
      DOMAIN: ((domain))
    on_success:
      aggregate:
      - put: cf-vars-s3
        params:
          file: cf-manifests/cf-variables.yml
      - put: cf-manifest-s3
        params:
          file: cf-manifests/cf.yml
  - task: cloud_config
    file: paas-bootstrap-git/ci/tasks/cf/cloud_config/task.yml
    params:
      ENVIRONMENT: ((environment))
      DOMAIN: ((domain))
    on_success:
      aggregate:
      - put: cf-cloud-config-s3
        params:
          file: cf-manifests/cloud-config.yml
  - task: deploy-stemcell
    file: paas-bootstrap-git/ci/tasks/cf/upload_stemcell/task.yml
  - task: deploy_cf
    file: paas-bootstrap-git/ci/tasks/cf/deploy_cf/task.yml

- name: verify-cf-endpoints
  serial: true
  plan:
  - get: paas-bootstrap-git
    passed: [deploy-cf]
    trigger: true
  - aggregate:
    - task: ensure CF api responds
      file: paas-bootstrap-git/ci/tasks/common/test_endpoint/task.yml
      params:
        HOST: api.system
        DOMAIN: ((domain))
        QUERY_PATH: /v2/info
    - task: ensure CF UAA responds
      file: paas-bootstrap-git/ci/tasks/common/test_endpoint/task.yml
      params:
        HOST: uaa.system
        DOMAIN: ((domain))
        QUERY_PATH: /info
        REQUIRE_JSON: true
