---
resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/ONSdigital/paas-bootstrap.git
    branch: master

jobs:
- name: pipeline-test
  plan:
  - get: git-repo
    trigger: true
  - task: verify
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: alpine, tag: latest }
      inputs:
      - name: git-repo

      run:
        path: ls
        args: [ git-repo ]
    