---
platform: linux
image_resource:
  type: docker-image
  source: { repository: onsdigital/paas-ci-gp, tag: latest }

inputs:
  - name: paas-bootstrap-git
  - name: cf-acceptance-tests-git
  - name: cf-vars-s3

outputs:
  - name: integration-config

run:
  path: paas-bootstrap-git/ci/tasks/cf/interpolate_cats/task.sh

params:
  DOMAIN: 
  ENVIRONMENT:
  CATS_CONFIG_FILE:
