---
platform: linux

image_resource:
  type: docker-image
  source: {repository: pivotalservices/cf-mgmt, tag: "latest"}

inputs:
  - name: paas-bootstrap-git
  - name: cf_mgmt_vars

run:
  path: paas-bootstrap-git/ci/tasks/management/task.sh

params:
  ENVIRONMENT:
